name: Node CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Run Application
        run: node app.js  

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
         name: output-file
         path: output.txt


      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
         name: build
         path: dist/   
