name: Node CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Run Application
        run: node app.js

      - name: Show Current Directory
        run: pwd

      - name: Show Files
        run: ls

      - name: Show Hidden Files
        run: ls -la

      - name: Upload Project
        uses: actions/upload-artifact@v4
        with:
          name: node-demo
          path: .
